# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 04643265c68165e595eb121a7ca833f7d2d9a4e0544812823c147f8e381779f24e5fafcaad9dddd5b96a3c31d1249806d82c76aafc003dc8e146e720e6f22894

test:
  secret_key_base: 5fbbfa3ac77e61cb40283411dc9dbf3221c37681e51b3a7d48a4c2dc9c64ea2d19dbe7985f9ca5af6f6c1dd021f317dedd864b660462d1f4484803d78a081027

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
